# Generated by Django 4.1.6 on 2023-03-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=11)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrinanalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('lab_code', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=20)),
                ('aspect', models.CharField(max_length=20)),
                ('blood', models.CharField(max_length=20)),
                ('urobilinogen', models.CharField(max_length=20)),
                ('bilirubin', models.CharField(max_length=20)),
                ('protien', models.CharField(max_length=20)),
                ('nitrite', models.CharField(max_length=20)),
                ('ketone_bodies', models.CharField(max_length=20)),
                ('glucose', models.CharField(max_length=20)),
                ('ph_level', models.CharField(max_length=20)),
                ('specific_gravity', models.CharField(max_length=20)),
                ('leukocyte_esterase', models.CharField(max_length=20)),
                ('rbcs', models.CharField(max_length=20)),
                ('pus_cells', models.CharField(max_length=20)),
                ('epithelial_cells', models.CharField(max_length=20)),
                ('calcium_oxalate', models.CharField(max_length=20)),
                ('uric_acid', models.CharField(max_length=20)),
                ('triple_phosphate', models.CharField(max_length=20)),
                ('amorphous', models.CharField(max_length=20)),
                ('microscopic_findings', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('lab_member_signature', models.CharField(max_length=50)),
                ('casts', models.CharField(max_length=20)),
                ('eggs', models.CharField(max_length=20)),
                ('mucus', models.CharField(max_length=20)),
                ('bacteria', models.CharField(max_length=20)),
                ('yeast', models.CharField(max_length=20)),
                ('sperm', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
    ]
