# Generated by Django 4.1.6 on 2023-03-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contraception_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cyanosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('date_of_birth', models.DateField(null=True)),
                ('occupation', models.CharField(default='', max_length=50)),
                ('mobile_number', models.CharField(max_length=11, null=True)),
                ('marriage', models.JSONField(default=dict, null=True)),
                ('education_level', models.CharField(choices=[('illiterate', 'Illiterate'), ('read and write', 'Read and Write'), ('primary', 'Primary'), ('preparatory', 'Preparatory'), ('secondary', 'Secondary'), ('university', 'University'), ('postgraduate', 'Postgraduate')], default='illiterate', max_length=50)),
                ('habits_of_medical_importance', models.JSONField(default=dict, null=True)),
                ('past_history', models.JSONField(default=dict, null=True)),
                ('family_history', models.JSONField(default=dict, null=True)),
                ('bp_high', models.IntegerField(null=True)),
                ('bp_low', models.IntegerField(null=True)),
                ('hr', models.IntegerField(null=True)),
                ('temp', models.IntegerField(null=True)),
                ('random_blood_sugar', models.IntegerField(null=True)),
                ('complexion', models.JSONField(default=dict)),
                ('complaints', models.JSONField(default=dict)),
                ('clinics', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrinAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], max_length=10)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('lab_code', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=20)),
                ('aspect', models.CharField(max_length=20)),
                ('blood', models.CharField(max_length=20)),
                ('urobilinogen', models.CharField(max_length=20)),
                ('bilirubin', models.CharField(max_length=20)),
                ('protien', models.CharField(max_length=20)),
                ('nitrite', models.CharField(max_length=20)),
                ('ketone_bodies', models.CharField(max_length=20)),
                ('glucose', models.CharField(max_length=20)),
                ('ph_level', models.CharField(max_length=20)),
                ('specific_gravity', models.CharField(max_length=20)),
                ('leukocyte_esterase', models.CharField(max_length=20)),
                ('rbcs', models.CharField(max_length=20)),
                ('pus_cells', models.CharField(max_length=20)),
                ('epithelial_cells', models.CharField(max_length=20)),
                ('calcium_oxalate', models.CharField(max_length=20)),
                ('uric_acid', models.CharField(max_length=20)),
                ('triple_phosphate', models.CharField(max_length=20)),
                ('amorphous', models.CharField(max_length=20)),
                ('microscopic_findings', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('lab_member_signature', models.CharField(max_length=50)),
                ('casts', models.CharField(max_length=20)),
                ('eggs', models.CharField(max_length=20)),
                ('mucus', models.CharField(max_length=20)),
                ('bacteria', models.CharField(max_length=20)),
                ('yeast', models.CharField(max_length=20)),
                ('sperm', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_img', models.ImageField(upload_to='')),
                ('back_img', models.ImageField(upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
    ]
