# Generated by Django 4.1.6 on 2023-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urinanalysisreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='penging', max_length=10),
            preserve_default=False,
        ),
    ]
