# Generated by Django 4.1.6 on 2023-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_patient_last_name_patient_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cyanosis',
        ),
        migrations.AlterField(
            model_name='patient',
            name='complexion',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
