# Generated by Django 4.1.6 on 2023-03-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_urinanalysisreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_History_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_checkup_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='Occupation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='abortion_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='contraception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='education_level',
            field=models.CharField(choices=[('illiterate', 'Illiterate'), ('read and write', 'Read and Write'), ('primary', 'Primary'), ('preparatory', 'Preparatory'), ('secondary', 'Secondary'), ('university', 'University'), ('postgraduate', 'Postgraduate')], default='illiterate', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='gravidal_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='mensturation',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('menopause', 'Menopause')], default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_cessation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.ManyToManyField(to='database.family_history_info'),
        ),
    ]
