# Generated by Django 4.1.6 on 2023-03-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_family_history_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraception_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='family_history_info',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Contraception_Info_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ManyToManyField(to='database.contraception_method')),
            ],
        ),
        migrations.CreateModel(
            name='Contraception_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraception', models.BooleanField(default=False)),
                ('method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.contraception_info_method')),
            ],
        ),
    ]
