# Generated by Django 4.1.6 on 2023-03-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_contraception_info_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contraception',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.contraception_info'),
        ),
    ]
