# Generated by Django 4.1.6 on 2023-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_patient_contraception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='abortion_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contraception',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gravidal_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mensturation',
        ),
        migrations.AlterField(
            model_name='contraception_info',
            name='methods',
            field=models.ManyToManyField(to='database.contraception_method'),
        ),
    ]
