# Generated by Django 4.1.6 on 2023-03-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_patient_abortion_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family_History_Info',
            new_name='Family_History',
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=50)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
    ]
