# Generated by Django 4.1.6 on 2023-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_patient_past_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smoking_cessation',
        ),
        migrations.AddField(
            model_name='patient',
            name='complaints',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='habits_of_medical_importance',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='marriage',
            field=models.JSONField(default=''),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='family_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.JSONField(default=''),
        ),
    ]
