# Generated by Django 4.1.6 on 2023-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_rename_occupation_patient_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patient',
            name='habits_of_medical_importance',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marriage',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_history',
            field=models.JSONField(default=dict),
        ),
    ]
