# Generated by Django 4.1.6 on 2023-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_patient_complaints_delete_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.JSONField(default=dict),
        ),
    ]
