# Generated by Django 4.1.6 on 2023-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_patient_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_history',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='habits_of_medical_importance',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marriage',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_history',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
