# Generated by Django 4.1.6 on 2023-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_patient_complaints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.TextField(default=list, null=True),
        ),
    ]
