# Generated by Django 4.1.6 on 2023-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_patient_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.TextField(default=list, null=True),
        ),
    ]
