# Generated by Django 4.1.6 on 2023-03-24 11:47

import database.primary_key
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_marriage_remove_patient_marriage_marriage_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code',
            field=database.primary_key.Code(default='THU0001', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
