# Generated by Django 4.1.6 on 2023-03-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_patient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prefix',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.IntegerField(),
        ),
    ]
