# Generated by Django 4.1.6 on 2023-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_patient_prefix_alter_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prefix',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
