# Generated by Django 4.1.6 on 2023-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prefix',
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
