# Generated by Django 4.1.6 on 2023-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_remove_patient_prefix_alter_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
